lib/SMQTK/Web/SMQTKSearchApp/modules/IQR/__init__.py

- Fixed issue #10
Was an issue of JSON data content key returned

Fixed error message shown when marking IQR elements as explicit

---

lib/SMQTK/Indexers/SVM.py

Added min requirement of N=1

---

lib/SMQTK/Web/SMQTKSearchApp/base_app.py
lib/SMQTK/Web/SMQTKSearchApp/modules/IQR/templates/iqr_search_index.html
requirements.txt

* Cleaned up default SMQTKSearchApp blueprint setup to only use default
system_config parameters.
* added missing scikit-learn requirement to requirements.txt file.
* Removed SMQTK from IQR web blueprint module header

Minor general updates

---

lib/SMQTK/FeatureDescriptors/__init__.py
lib/SMQTK/Indexers/__init__.py
lib/SMQTK/utils/plugin.py

Replaced existing plugin method meat in FeatureDetectors and Indexers modules with a call the the now common get_plugins method.

Added generic plugin class loader using common rules

---

bin/CreateIngest.py
lib/SMQTK/utils/DataIngest.py
lib/SMQTK/utils/VideoIngest.py

make further use of md5 in filenames

Added ingest initialization optimization

---

bin/GenerateModel.py
python/SMQTK/FeatureDescriptors/colordescriptor/csift2.py
python/SMQTK/FeatureDescriptors/colordescriptor/utils.py
python/SMQTK/Fusion/Catalyst/Average.py
python/SMQTK/Indexers/SVM.py
python/SMQTK/Web/SMQTKSearchApp/modules/IQR/static/js/smqtk.progress_bars.js
python/SMQTK/Web/SMQTKSearchApp/modules/IQR/templates/iqr_search_index.html

Plus:
- KMeans algo source change
- additional debugging messages/timers
- threading level specifier to model generation script

Content description robustness update

---

README.md

Tiny change to see if I can add branches directly to the repo. For me this has less friction so I think I will do it this way. @Purg would this mode also work for you? Easier to hand off co-developing and finding branches.

Adding project name to README

---

python/smqtk/web/geospace/deploy/docker/Dockerfile

@Purg minor change. Just need to get rid of a special branch

No longer we need to checkout a special branch for docker

---

python/smqtk/web/imagespace/web_external/js/views/layout/UserDataView.js
python/smqtk/web/imagespace/web_external/templates/body/frontPage.jade
python/smqtk/web/imagespace/web_external/templates/widgets/imageDetailWidget.jade

Save search url with saved image

---

python/smqtk/web/imagespace/web_external/js/views/widgets/ImageDetailWidget.js

Fix ability to refine an image similarity search

---

python/smqtk/web/imagespace/web_external/stylesheets/layout.styl

Fixing scroll bar appearance on Firefox

---

.travis.yml
python/smqtk/fusion/catalyst/average.py
python/smqtk/utils/database_info.py
requirements.txt

Working my way to understanding what to do here.

Travis-CI integration

---

README.md
bin/computeFeature.py
bin/generateModel.py
etc/system_config.json
python/smqtk/content_description/__init__.py
python/smqtk/content_description/colordescriptor/colordescriptor.py
python/smqtk/content_description/colordescriptor/encode_FLANN.py
python/smqtk/data_rep/__init__.py
python/smqtk/data_rep/data_element_abstract.py
python/smqtk/data_rep/data_element_impl/file_element.py
python/smqtk/data_rep/data_element_impl/memory_element.py
python/smqtk/data_rep/data_element_impl/url_element.py
python/smqtk/data_rep/data_set_abstract.py
python/smqtk/data_rep/descriptor_element_abstract.py
python/smqtk/data_rep/descriptor_element_factory.py
python/smqtk/data_rep/descriptor_element_impl/local_elements.py
python/smqtk/similarity_index/__init__.py
python/smqtk/similarity_index/flann.py
python/smqtk/similarity_nn/__init__.py
python/smqtk/similarity_nn/flann.py
python/smqtk/utils/configuration.py
python/smqtk/utils/plugin.py
python/smqtk/web/descriptor_service/server.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py

Added separated module for similarity nearest-neighbor indexing given single exemplar. This is a stepping stone for an IQR Index module with a swapable nearest-neighbor function.

Similarity indexing module

---

python/smqtk/data_rep/descriptor_element_impl/local_elements.py

Fixed relative path handling in DescriptorFileElement class

---

python/smqtk/data_rep/descriptor_element_abstract.py
python/smqtk/similarity_index/__init__.py
python/smqtk/similarity_index/flann.py

Added save/load index methods to similarith index interface

---

python/smqtk/utils/string_utils.py

It now works as probably expects.

fix string partition util

---

python/smqtk/content_description/__init__.py
python/smqtk/content_description/colordescriptor/colordescriptor.py
python/smqtk/data_rep/data_element_impl/url_element.py
python/smqtk/utils/plugin.py
python/smqtk/web/descriptor_service/server.py

Add call points to compute all possible descriptors for a given data element specification based on matching data content type to available descriptors that can handle that type.

Descriptoer Service Server - Batch descriptor computation given data element

---

python/smqtk/data_rep/data_element_abstract.py

For simplicity's sake.
This can be changed in the future if performance becomes an issue

Use list instead of deque

---

python/smqtk/data_rep/data_set_impl/file_set.py
python/smqtk/tests/data_rep/DataSet/test_FileSet.py

Only writes to file if there have been set modifications.

Condutionalize file-set serialization

---

python/smqtk/content_description/colordescriptor/colordescriptor.py

This is incorrect because not all available descriptors produce vectors
of length 382, like SIFT, which produces vectors of lenght 128.

Fixed some hard-coding that manually set base descriptor length

---

etc/system_config.json
python/smqtk/similarity_index/__init__.py
python/smqtk/similarity_index/flann.py
python/smqtk/similarity_index/lsh/code_index/__init__.py
python/smqtk/similarity_index/lsh/code_index/memory.py
python/smqtk/similarity_index/lsh/itq.py
python/smqtk/utils/configuration.py

Common bit-code to descriptor index abstraction and in-memory implementation.

LSH-class algorithm index abstraction

---

.travis.yml

Didn't need to use sudo other than for package installation, for which there is now an alternate method.

Updated travis-CI to use new container infrastructure

---

python/smqtk/content_description/colordescriptor/colordescriptor.py
python/smqtk/data_rep/data_element_abstract.py

While helping Roddy, these are some issues that we encountered, thus fixing them.

Some Fixes

---

etc/system_config.json
python/smqtk/content_description/colordescriptor/colordescriptor.py
python/smqtk/data_rep/data_element_abstract.py
python/smqtk/data_rep/data_element_impl/file_element.py
python/smqtk/data_rep/data_element_impl/memory_element.py
python/smqtk/data_rep/data_element_impl/url_element.py
python/smqtk/data_rep/data_set_impl/file_set.py

- add autotune algo choice to colordescriptor constructor

Change hash usage to sha1 from md5

---

README.md
python/smqtk/data_rep/data_element_abstract.py

Also updated the simple descriptor computation example to include the
use of descriptor element factories.

Updated top-level README.md file with CMake build instructions

---

python/smqtk/data_rep/data_element_impl/memory_element.py
python/smqtk/data_rep/data_element_impl/url_element.py
python/smqtk/utils/plugin.py

Added methods that can be used for expanding objects from potentially
nested configuration dictionaries.

Generic plugin object configuration functions

---

bin/scripts/runners/memex.dyndns/process_roxyimages.csift.py
bin/scripts/runners/memex_hbase_gpu_machine/cnn_config.prototxt.tmpl
bin/scripts/runners/memex_hbase_gpu_machine/compute.py

Removed specific HBase address used in one script in case it would have been a security issues.

Added scripts used on machines for remove batch processing of descriptors

---

.travis.yml
requirements.pip.txt

Moved it to pip requirements file where it should be.

Removed explicit install of gmpy2 in .travis.yml

---

.travis.yml
python/smqtk/content_description/__init__.py
python/smqtk/data_rep/code_index/memory.py
python/smqtk/data_rep/data_element_abstract.py
python/smqtk/data_rep/data_element_impl/file_element.py
python/smqtk/data_rep/descriptor_element_abstract.py
python/smqtk/indexing/svm_hik.py
python/smqtk/iqr_index/__init__.py
python/smqtk/iqr_index/libsvm_hik.py
python/smqtk/similarity_index/flann.py
python/smqtk/similarity_index/lsh/itq.py
python/smqtk/tests/data_rep/DescriptorElement/test_DescriptorElement_abstract.py
python/smqtk/tests/utils/test_distance_functions.py
python/smqtk/utils/configurable_interface.py
python/smqtk/utils/distance_functions.py
python/smqtk/utils/distance_kernel.py
python/smqtk/utils/plugin.py
requirements.pip.txt

Plus various other revisions:
- improved impl + documentation on HI distance functions in ``smqtk.utils.distance_functions`` (and renamed them appropriately).
- small optimization to ITQ nearest-neighbor method.
- tests for HI distance functions
- new distance kernel/matrix computation functions in ``smqtk.utils.distance_kernel`` module.
Room for performance improvements (time+space) is probable in SVM-HIK implementation.

New IQR Index interface + SVM HIK implementation

---

python/smqtk/utils/preview_cache.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py
python/smqtk/web/search_app/modules/static_host.py

So we can stop requiring that we write files in the source tree while running the server.

Blueprint for IQR app to host custom directory as static dir

---

python/smqtk/algorithms/descriptor_generator/colordescriptor/colordescriptor.py

Now correctly checks if the colorDescriptor executable and support is
usable and records the result correctly. Before, we were accidentally
recording it as usable 100% of the time regardless of test outcome.
Added to the warning output what stdout/stderr output of the test call
to colorDescriptor included. This may help with debugging why its not
being accepted by the plugin system due to a missing library or
something.

Revised ColorDescriptor wrapper impl of is_usable

---

bin/summarizePlugins.py
docs/architecture.md
python/smqtk/algorithms/descriptor_generator/__init__.py
python/smqtk/algorithms/nn_index/__init__.py
python/smqtk/algorithms/relevancy_index/__init__.py
python/smqtk/representation/code_index/__init__.py
python/smqtk/representation/data_element/__init__.py
python/smqtk/representation/data_set/__init__.py
python/smqtk/representation/descriptor_element/__init__.py
python/smqtk/representation/descriptor_index/__init__.py
python/smqtk/tests/utils/test_plugin_dir/external_1.py
python/smqtk/tests/utils/test_plugin_dir/external_2.py
python/smqtk/tests/utils/test_plugin_dir/internal_plugins/__init__.py
python/smqtk/tests/utils/test_plugin_dir/internal_plugins/implNormal.py
python/smqtk/tests/utils/test_plugin_dir/internal_plugins/implPartial.py
python/smqtk/tests/utils/test_plugin_dir/internal_plugins/implSkip.py
python/smqtk/tests/utils/test_plugin_get.py
python/smqtk/tests/utils/test_plugin_tools.py
python/smqtk/utils/plugin.py

A little bit if restructuring of the generalized function call to allow for PATH-like specification of out-of-source modules that provide interface plugins.

Plugin Update

---

bin/scripts/runners/memex_hbase_gpu_machine/itq_training/add_codes.py
bin/scripts/runners/memex_hbase_gpu_machine/itq_training/load_algo.py
bin/scripts/runners/memex_hbase_gpu_machine/itq_training/train_model.py

Small tweaks and optimizations made while working with them.

ITQ training scripts tweaks

---

bin/scripts/runners/itq_training/load_algo.py
bin/scripts/runners/itq_training/train_model.py
docs/algorithminterfaces.rst
docs/dataabstraction.rst
docs/release_notes/since-last-release.md
docs/webservices/iqrdemonstration.rst
python/smqtk/algorithms/nn_index/lsh/functors/__init__.py
python/smqtk/utils/bit_utils.py
python/smqtk/web/search_app/config.IqrSearchApp.json
python/smqtk/web/search_app/config.classifyFiles.json

... and update them with correct text and references.
Basically stuff that I missed to update in the LSH overhaul branch.

Updated documents and other files to remove ITQ NN-Index impl references

---

CONTRIBUTING.md
docs/building.rst
docs/release_notes/since-last-release.md

plus typo fix in building documentation

Added basic CONTRIBUTING.md file

---

bin/memex/run.update.sh

Bug in how it was checking previous run completion.

Fixed update script

---

bin/runApplication.py
docs/examples/nnss_incremental_update/incremental_example.rst
docs/release_notes/since-last-release.md
python/smqtk/algorithms/classifier/__init__.py
python/smqtk/algorithms/classifier/libsvm.py
python/smqtk/algorithms/nn_index/lsh/__init__.py
python/smqtk/algorithms/relevancy_index/libsvm_hik.py
python/smqtk/iqr/iqr_controller.py
python/smqtk/iqr/iqr_session.py
python/smqtk/representation/descriptor_index/postgres.py
python/smqtk/tests/algorithms/relevancy_index/test_iqr_svm_hik.py
python/smqtk/web/__init__.py
python/smqtk/web/descriptor_service/__init__.py
python/smqtk/web/iqr_service/__init__.py
python/smqtk/web/iqr_service/api.rst
python/smqtk/web/nearestneighbor_service/__init__.py
python/smqtk/web/search_app/__init__.py
python/smqtk/web/search_app/modules/file_upload/FileUploadMod.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py
python/smqtk/web/search_app/modules/iqr/static/js/smqtk.iqr_view.js
python/smqtk/web/search_app/modules/login/LoginMod.py
python/smqtk/web/search_app/static/js/smqtk.alerts.js

Still needs state for session management, but hey, its my first time.
Includes other updates and bug fixes.

IQR service mostly-RESTful service

---

bin/memex/get_cdr_images.py
bin/scripts/compute_hash_codes.py
bin/scripts/compute_many_descriptors.py
docs/release_notes/since-last-release.md
python/smqtk/compute_functions.py
python/smqtk/representation/descriptor_index/postgres.py

Like:
- Lazy connection during postgres descriptor index batch operations
- remove int cast for parameters in get_cdr_images
- tweaked some logging messages
- added progress reporting to many-descriptor computation script
- added release note

Various updates to minor things

---

bin/classifier_model_validation.py
bin/descriptors_to_svmtrainfile.py
python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py
requirements.optional.txt

Changes and fixes from the UK Image hack event:
- Added confusion matrix output in classifier validation utility.
- Added formal logging to descriptor-to-libsvmfile utility
- Added pixel input scale parameter to Caffe descriptor generator. Pixel re-scale range still applied BEFORE Caffe Transformer application (i.e. mean image subtraction occurs after pixel re-scale if provided).

UK image hack

---

bin/compute_hash_codes.py
bin/generate_image_transform.py
python/smqtk/utils/bin_utils.py

Added utility script that can perform a number of simple transformations and crops to an input image, which is not modified, and output a series a new image files for the crops/transformations performed.
Also, some random fixes.

Image transform util

---

python/smqtk/algorithms/nn_index/lsh/functors/itq.py

If not None, used to normalize descriptors input to fitting and for hash code generation. This is implemented in the same way as normalization is in the libSVM classifier implementation.

Added optional descriptor normalization to ITQ functor

---

python/smqtk/utils/distance_kernel.py

Using internal parallel map iterator.

Added parallel option to distance kernel generation

---

bin/classifier_model_validation.py

Turns out the matrix normalization was incorrect due to a bad array
division (wasn't the correct shape before).

Renamed some vars for clarity + fixed plotting of confusion matrix

---

TPL/libsvm-3.1-custom/tools/grid.py
bin/classifyFiles.py
bin/memex/hackathon_2016_04/save_ad_images.py
bin/memex/hackathon_2016_04/save_phone_images.py
bin/memex/hackathon_2016_04/score_phone_numbers.py
python/smqtk/algorithms/classifier/__init__.py

Scripts and fixes developed during hackathon week.

2016/04 Hackathon scripts

---

bin/classifier_model_validation.py
bin/memex/hackathon_2016_04/ad-images.split-train-test.py

Some additional fixed/updates from post-hackathon re-evaluation

Hackathon dev part 2

---

docs/release_notes/since-last-release.md

Haven't been properly updating the release notes file for the last many commits. This adds relevant notes for differences between master and the last release.

Update release notes

---

docs/release_notes/v0.6.0.md
python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py
python/smqtk/algorithms/nn_index/lsh/functors/itq.py
python/smqtk/utils/bin_utils.py
python/smqtk/utils/parallel.py

Some small fixes/updates found here and there.

Small Fixes

---

docker/smqtk_services.run_images.sh
docs/release_notes/v0.6.1.md
python/smqtk/web/iqr_service/__init__.py

Fix docker scripts to reflect correct container name

---

docker/smqtk_services.run_images.sh

Remove the automatic tailing of logs at end of docker script

---

bin/memex/hackathon_2016_07/notebooks/CP1 Data Curation.ipynb

Updated the notebook and added docs. 
Though it was aimed for CP1 - this type of process is pretty general, so maybe this can help out in the future.

Simplify and document CP1 notebook

---

setup.py

Fix syntax error in setup.py introduced by a47026b

---

python/smqtk/bin/runApplication.py

This error got introduced in d0a5e194e2fd844da2cff5c1444b2d2bc2c52410 and I apparently brought it up in #294 without fixing it :-/.

Fix undefined variable config in runApplication

---

python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py

Fix a bug referencing non-existent kwds variable introduced in #302

---

python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py

Should solve deprecation warning.

Update caffe Net class construction to current form.

---

.travis.yml
requirements.optional.txt
requirements.txt
setup.py

Additionally updated version numbers for other packages and commented out everything in the optional requirements file by default. Updated pull of miniconda installer to the current miniconda2 URL.

Fix travis CI build

---

.travis.yml

This doesn't look like its even used anywhere.

Remove LOCAL_ROOT setup from travis

---

docs/release_notes/v0.7.0.md

Add short header description of some major release details

---

python/smqtk/representation/key_value/postgres.py
python/smqtk/tests/representation/KeyValueStore/test_PostgresKeyValueStore.py

Fix PostgreSQL KVS implementation to remove correctly

---

docs/release_notes/pending_release.rst
python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py

Now call the appropriate caffe set-mode function in the work function.

Fix caffe impl GPU mode bug

---

devops/docker/smqtk_iqr_playground/README.md
docs/release_notes/pending_release.rst

Amended IQR docker image README.md file to provide more clarity in building and running the docker images.

Updated IQR docker image README for better clarity of instruction

---

devops/docker/smqtk_wrapper_python/requirements.txt
docs/release_notes/pending_release.rst
requirements.txt

I was apparently too quick on the uptake for the first one to realized there where 3 more alerts.

More version updates as recommended by GitHub alert

---

docs/release_notes/pending_release.rst
python/smqtk/web/search_app/__init__.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py
python/smqtk/web/search_app/modules/iqr/static/js/smqtk.iqr_view.js
python/smqtk/web/search_app/modules/login/templates/login.html
python/smqtk/web/search_app/static/js/smqtk.vars.js
python/smqtk/web/search_app/templates/base.html

Attempted to address a CSRF vulnerability with the demo web front end. Being a demonstration webapp not for production use, this is not a super critical issue.

Fix CSRF vulnerability in demo IQR web-app

---

python/smqtk/algorithms/nn_index/lsh/__init__.py
python/smqtk/algorithms/nn_index/lsh/functors/itq.py
python/smqtk/algorithms/relevancy_index/libsvm_hik.py
python/smqtk/bin/compute_hash_codes.py
python/smqtk/bin/iqr_app_model_generation.py
python/smqtk/representation/data_set/file_set.py
python/smqtk/representation/data_set/memory_set.py
python/smqtk/representation/descriptor_element/_io.py
python/smqtk/representation/descriptor_index/memory.py
python/smqtk/representation/descriptor_index/postgres.py
python/smqtk/tests/algorithms/nn_index/lsh_hash_functors/test_itq.py
python/smqtk/tests/representation/ClassificationElement/test_CE_abstract.py
python/smqtk/tests/utils/test_image_utils.py
python/smqtk/utils/parallel.py
scripts/memex/hackathon_2016_07/cp1/data_retreival/scripts/download_url_as_sha.py

Miscellaneous fixes to imports and exception handling.

Fix various misc issues

---

requirements.txt

Based on recommended security update.

Update patch ver of jinja2

---

.travis.yml
docs/release_notes/pending_release.rst
python/smqtk/web/iqr_service/iqr_server.py

Update Travis-CI configuration due to changes in defaults.

Update travis CI configuration
