python/smqtk/content_description/colordescriptor/colordescriptor.py

... when determining component parallelism in video version of ColorDescriptor implementation.
Otherwise the pool construction calls fail (range under the hood requires int).

Added missing integer casting

---

python/smqtk/data_rep/data_element_abstract.py
python/smqtk/data_rep/data_element_impl/file_element.py
python/smqtk/data_rep/data_set_impl/file_set.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py
python/smqtk/web/search_app/modules/iqr/static/js/smqtk.iqr_result.js

+ fix some data element temp file issues
When clicking on the query results in the main window, the window that opens up isn't just the preview data, but a link to a statically-served copy of the actual data as a file server-side.
This won't work with an install of SMQTK, if one manages to do that in the first place, this will probably lead to permission issues (writing to root owned space), but this is supposed to be a demo app anyway.

IQR Webapp serve static files

---

.travis.yml
nose_exclude_dirs.txt
python/smqtk/content_description/colordescriptor/colordescriptor.py
python/smqtk/content_description/colordescriptor/utils.py
requirements.txt

Being an optional dependency, an exception shouldn't be emitted by merely importing the SMQTK module, but informed at runtime that its not available.
Addresses issue #72

Remove colorDescriptor import error on nosetest

---

python/smqtk/content_description/colordescriptor/colordescriptor.py
python/smqtk/web/descriptor_service/server.py

Instead of just returning a "INTERNAL SERVER ERROR" when a descriptor
type is given an data type it can't handle, returns a JSON message with
False success and a message that describes the issue.
Also added missing super-call to colordescriptor `compute_descriptor()` implementation.

Gracefully handle data of invalid content type for a descriptor

---

etc/system_config.json
python/smqtk/content_description/__init__.py
python/smqtk/content_description/colordescriptor/colordescriptor.py
python/smqtk/data_rep/data_element_impl/file_element.py
python/smqtk/data_rep/data_set_impl/file_set.py
python/smqtk/utils/__init__.py

Allow configuration of data file-sets and data file-element (in factory config) to take relative paths.

Use relative paths

---

README.md

Adds Travis CI status badge to README.md file for graphical display when markdown is rendered (with access to the internet, i.e. GitHub).

Add travis ci image

---

.gitignore
.travis.yml
run_tests.sh

Now, users that want to run tests in their console will run the same
thing that travis-CI is running (and vice-versa).

Added test runner script

---

python/smqtk/data_rep/descriptor_element_impl/local_elements.py

... in relation to the configured ``save_dir``.
This helps when there will be many many descriptors. Without this, they
would all be put into the same directory, which would grow to inoperable
sizes. Splitting into sub-directories based on the provided UUID
string-ification branches this out so that no one directory has to have
an unmanageable number of files in it.

Added option to store local-files in a standard subdirectory

---

python/smqtk/data_rep/data_element_abstract.py

Because its still a thing where non-standard jpeg extensions can get
priority in python's mimetypes module

Added another exeption for silly jpeg mimetypes

---

.travis.yml
python/smqtk/similarity_index/flann.py
python/smqtk/similarity_index/lsh/code_index/__init__.py
python/smqtk/similarity_index/lsh/code_index/memory.py
python/smqtk/similarity_index/lsh/code_index/solr_index.py
python/smqtk/similarity_index/lsh/itq.py
python/smqtk/utils/bit_utils.py
python/smqtk/utils/distance_functions.py
requirements.pip.txt

Two primary fixes:
* modified ITQ index's ``nn`` method to not use bit-vector permutation, which is infeasible for large bit vector lengths, to a hamming distance computation and sort using heap-based priority queue.
* Fixed bug with bit-vector-to-int transformation function. Had an issue where the numpy int type was poluting the python int type and causing overflow issues instead of int->long extension. This was exposed when experimenting with larger bit vector sizes.
The `nn` function could probably be improved further by using a data structure that is initialized at index creation tile which allows for distance-based neighbor querying. Attempted the use of a VP-tree (https://en.wikipedia.org/wiki/Vantage-point_tree) using the python implementation that is linked on the wiki page, but …

Better itq nn

---

python/smqtk/data_rep/descriptor_element_abstract.py
python/smqtk/data_rep/descriptor_element_factory.py
python/smqtk/data_rep/descriptor_element_impl/local_elements.py
python/smqtk/tests/data_rep/DescriptorElement/test_DescriptorMemoryElement.py

Because the DescriptorMemoryElement uses a class variable to cache data in, when pickling an instance, this cache didn't get drawn into it, so loading the pickled class in a different process or at a different time yielded the element to think it didn't have an associated vector, defeating the point of having pickled it in the first place.
Now, we implement custom state get/set methods that encode an element's numpy vector if one was set on it, restoring it to the cache when loaded.

Fix DescriptorMemoryElement pickling issue

---

.travis.yml
python/smqtk/tests/utils/test_distance_functions.py
python/smqtk/utils/distance_functions.py
requirements.pip.txt
run_tests.sh

Less than easy to set up and packaging them is problematic because of GPL/LGPL licenses.

Remove gmpy2 dependency

---

bin/scripts/iqr_app_model_generation.py
python/smqtk/representation/data_element/__init__.py
python/smqtk/representation/data_set/__init__.py
python/smqtk/representation/data_set/file_set.py
python/smqtk/representation/data_set/memory_set.py
python/smqtk/representation/descriptor_element/__init__.py
python/smqtk/tests/representation/DataSet/test_DataSet_abstract.py
python/smqtk/tests/representation/DataSet/test_FileSet.py
python/smqtk/tests/representation/DataSet/test_MemorySet.py
python/smqtk/tests/representation/DataSet/test_plugins.py
python/smqtk/utils/file_utils.py
python/smqtk/web/search_app/config.IqrSearchApp.json

Fixes discovered and made while writing some documentation.
* Separated out old DataFileSet into DataMemorySet and DataFileSet, as the old implementation acted like both.
* Cleaned up repeated metaclass assignments
* updated directory file iterator to use ``os.walk``
* Updated configuration file use of ``uuid_chunk`` (used to be ``sha1_chunk``).

Misc fixes

---

python/smqtk/algorithms/nn_index/flann.py
python/smqtk/tests/algorithms/nn_index/test_NNI_FLANN.py

Now, when no file paths are provided, model is only maintained in memory
and lost when instance is deleted. Desired so the implementation doesn't write files to disk when used naively.

Removed default FLANN model filepaths

---

python/smqtk/iqr/iqr_session.py
python/smqtk/web/__init__.py
python/smqtk/web/descriptor_service/__init__.py
python/smqtk/web/search_app/__init__.py

Current implementations should always be available, this their ``is_usable`` impls just return true.

Fix web module interface to use Pluggable interface

---

bin/scripts/iqr_app_model_generation.py
python/smqtk/algorithms/descriptor_generator/colordescriptor/colordescriptor.py
python/smqtk/algorithms/nn_index/flann.py
python/smqtk/web/search_app/config.IqrSearchApp.json

When using HIK distance type, things are returned in an inverse fashion that was is normally desired, this the same fix that is implemented in the FLANN implementation of the NearestNeighborsIndex interface was added to the colordescriptor manual BoW impl.
Also updated the IQR model gen script to read from a JSON configuration file for the web app instead of encoding its own configuration dictionaries, removing the need for the user to have to manually synchronize the configuration in that script with their configuration file for the application.

Fix ColorDescriptor interface BoW impl

---

python/smqtk/iqr/iqr_session.py

Was accidentally set to the wrong value.

Fix default rel-index valid

---

bin/scripts/runners/memex_hbase_gpu_machine/compute.py
bin/scripts/runners/memex_hbase_gpu_machine/itq_training/add_codes.py
bin/scripts/runners/memex_hbase_gpu_machine/itq_training/load_algo.py
bin/scripts/runners/memex_hbase_gpu_machine/itq_training/train_model.py
python/smqtk/algorithms/descriptor_generator/__init__.py
python/smqtk/algorithms/descriptor_generator/caffe_default_imagenet/__init__.py
python/smqtk/algorithms/descriptor_generator/caffe_default_imagenet/cnn_config.prototxt.tmpl
python/smqtk/algorithms/descriptor_generator/caffe_default_imagenet/descriptor.py
python/smqtk/algorithms/nn_index/lsh/itq.py
python/smqtk/algorithms/relevancy_index/libsvm_hik.py
python/smqtk/representation/data_element/hbase_element.py
python/smqtk/representation/data_set/memory_set.py
python/smqtk/representation/descriptor_element/__init__.py
python/smqtk/representation/descriptor_element/_io.py
python/smqtk/tests/representation/DataSet/test_MemorySet.py
python/smqtk/utils/configurable_interface.py
setup_env.build.sh.in

- Added wrapper for CNN descriptor generation executable optionally built in SMQTK
- Added additional scripts used on GPU computation machine for MEMEX
- Added HBase DataElement implementation
- Added async conversion of DescriptorElement instances into a 2D numpy.ndarray
- Fixed Configurable.get_default_config() for sub-classes that don't explicitly implement an __init__ constructor method.
- Fixed bug with libSVM relevancy index to now work with distances less than -1 (e.g. using HIK on CNN vectors)
- Added file cache backing option to DataMemorySet.
- Updated tests
- Added SMQTK_SOURCE env variable export in build-focused setup script

CNN and HBase update for IQR

---

bin/scripts/iqr_app_model_generation.py
python/smqtk/algorithms/descriptor_generator/caffe_default_imagenet/descriptor.py
python/smqtk/iqr/iqr_session.py
python/smqtk/representation/code_index/__init__.py
python/smqtk/representation/code_index/memory.py
python/smqtk/representation/code_index/solr_index.py
python/smqtk/representation/data_element/__init__.py
python/smqtk/representation/data_set/file_set.py
python/smqtk/tests/representation/DataElement/test_DataElement_abstract.py
python/smqtk/tests/representation/DataElement/test_DataFileElement.py
python/smqtk/tests/representation/code_index/test_abstractCodeIndex.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py

- Added various amounts of new logging.
- Now read DescriptorElementFactory config from IQR-app configuration when training for app.
- Updated function of repeated IQR-app working index initialization to only additionally query for neighbors to positives added since the last initialization in the same session. Cache cleared on session reset. This means we only add to the session working session when re-initializing.
- Added to ``DataElement.write_temp()`` to clear temp files that don't exist on dist before checking whether it should write a temp file. This adds robustness to files disappearing on disk during run-time.
- Fixed DataFileSet file element path resolution when ``uuid_chunk`` is 0 or None or other False-evaluating value.
- Fixed an issue where clicking on an image to open in a …

File/IQR/Logging Updates

---

python/CMakeLists.txt

Removed install command for directories not there anymore. Tested full build and install on a fedora 23 box, which now works (I see little reason why it wouldn't work elsewhere, but let me know).

Fix smqtk python cmake install code

---

TPL/libsvm-3.1-custom/svm.cpp
bin/iqrTrainClassifier.py
docs/release_notes/since-last-release.md
python/smqtk/algorithms/__init__.py
python/smqtk/algorithms/classifier/__init__.py
python/smqtk/algorithms/classifier/libsvm.py
python/smqtk/iqr/iqr_controller.py
python/smqtk/utils/plugin.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py

Primarily added a script to train a supervised classifier based on positive/negative adjudication output of an IQR session.
Other changes:
- Added ``SupervisedClassifier`` intermediate abstract class for trainable classifiers given class examples.
- Fixed libSVM customization that would cause ``free()`` issues in certain cases, as well as caused an additional file to be written. These both only happened when the SVM being saved was 2-class.
- Updated ``get_plugins`` function to handle skipping intermediate abstract classes.

IQR session supervised classifier trainer

---

python/smqtk/representation/classification_element/file.py

Otherwise exceptions are thrown when trying to set the classification value when base save directories don't exist.

Added directory creation if it didn't exist

---

docs/release_notes/since-last-release.md
python/smqtk/web/nearestneighbor_service/__init__.py

Added additional URI format to allow for sub-query return based on start and end neighbor indices. This allows a user to over-query and only ask for a slice of the computed query.

Add "pagination" to nearest neighbor service

---

bin/iqrTrainClassifier.py
bin/iqr_app_model_generation.py
docs/release_notes/since-last-release.md
python/smqtk/iqr/iqr_session.py
python/smqtk/representation/descriptor_element/__init__.py
python/smqtk/representation/descriptor_element/local_elements.py
python/smqtk/tests/algorithms/classifier/test_libsvm.py
python/smqtk/tests/algorithms/nn_index/test_NNI_FLANN.py
python/smqtk/tests/algorithms/nn_index/test_NNI_abstract.py
python/smqtk/tests/algorithms/nn_index/test_NNI_itq.py
python/smqtk/tests/algorithms/relevancy_index/test_iqr_svm_hik.py
python/smqtk/tests/representation/DescriptorElement/test_DescriptorFileElement.py
python/smqtk/tests/representation/DescriptorElement/test_DescriptorMemoryElement.py
python/smqtk/tests/representation/code_index/test_MemoryCodeIndex.py
python/smqtk/tests/representation/code_index/test_abstractCodeIndex.py
python/smqtk/tests/representation/test_DescriptorElementFactory.py
python/smqtk/utils/distance_functions.py
python/smqtk/web/search_app/static/js/smqtk.alerts.js

This PR primarily motivated by DescriptorMemoryElement vector storage being mutable after vector (numpy array views) were stored. Discovered when descriptor output from CaffeDescriptorGenerator.compute_descriptor_async was outputting duplicate descriptors for distinctly different input data elements. This occurred because descriptors were being pulled from a layer matrix in caffe's network. Vectors being stored in memory descriptor elements were actually array views. Thus, when caffe overwrote the result layer during the next feed-forward, the views updated, too, causing the array views already stored to return something different and incorrect.
This branch also bundles in it the following additional fixes found in the process of this hunt:
* bug fix in IQR session where it wasn't …

Fix: caffe memory descriptor interaction

---

TPL/libsvm-3.1-custom/svm.cpp
docs/release_notes/since-last-release.md

log2 doesn't exist until VS 2013.  Add it here.

add log2 for older win compilers (<2013)

---

docs/architecture.rst
python/smqtk/algorithms/nn_index/lsh/functors/__init__.py
python/smqtk/utils/__init__.py
python/smqtk/utils/plugin.py

Its definitely not markdown any more, so I cleaned that up.

Touched up architecture overview doc for typos and linkages

---

bin/memex/run.update.sh
python/smqtk/web/iqr_service/__init__.py
python/smqtk/web/nearestneighbor_service/__init__.py

This is basically a duplication of the functionality provided by the descriptor service, but only uses the single generator configuration. Hooks into updating the configured descriptor index if the service is configured for index updating.

NNSS compute descriptor endpoint

---

bin/compute_hash_codes.py
bin/compute_many_descriptors.py
python/smqtk/compute_functions.py

Before, performed explicitly image content specific actions on input
data, which is not generically guarenteed. Added CLI option to
optionally enable those checks when user knows input data is going to be
imagery. Moved byte loading check from base compute function into the
utility script.

Removed explicit image data dependence from util

---

python/smqtk/algorithms/descriptor_generator/__init__.py
python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py

Defaulted in the interface as well as in the Caffe generator option.
Defaults can be added to other less used implementations when necessary
at a later time.

Added a default factory for descriptor generators

---

python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py
python/smqtk/compute_functions.py

Wasn't correctly iterating over elements when ``file_elements`` iterated the second time. Introduced a small internal wrapper function that captures iterated elements into a ``deque``.

Fixed bug with element iteration in ``compute_many_descriptors`` function

---

CMakeLists.txt
docs/release_notes/since-last-release.md
python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py
python/smqtk/algorithms/nn_index/flann.py
python/smqtk/representation/data_element/file_element.py
python/smqtk/tests/algorithms/nn_index/test_NNI_FLANN.py
python/smqtk/tests/representation/DataElement/test_DataFileElement.py
python/smqtk/utils/distance_functions.py
python/smqtk/utils/distance_kernel.py
python/smqtk/web/nearestneighbor_service/__init__.py

- Added more comments/detail in places.
- fixed caffe descriptor batch logging counter
- Added use of elements_to_matrix function in FLANN nn-index instead of
performing the old serial version.
- fixed FLANN nn function to return a list like the docstring states instead
of a numpy.ndarray.
- Removed absolute-path transformation from DataFileElement class constructor,
allowing the recording of a dataset using relative paths, which is more
transportable.
- declared explicit use of threading in ``compute_distance_kernel`` function

Various updates and fixes

---

docs/release_notes/v0.6.0.md
python/smqtk/iqr/iqr_controller.py
python/smqtk/web/iqr_service/__init__.py
python/smqtk/web/search_app/modules/iqr/iqr_search.py

When supporting a long-term service, IQR sessions and classifiers need to be cleaned otherwise RAM would get overrun by sessions that are no longer used. Session expiration has been added as an optional feature to the ``IqrController`` class that also allows registration of a callback function, which the IqrService leverages to also clean up classifiers (and other future associated resources).

iqr service session expiration

---

docker/smqtk_services/iqr.config.json
docs/release_notes/v0.6.1.md
python/smqtk/iqr/iqr_session.py
python/smqtk/web/iqr_service/__init__.py

This also solves a specific issue that @danlamanna brought to attention.  The issue is that the try catch is catching any KeyError that might get raised, and the message assumes that it must be a session ID related issue, which it might not be, such as in this case.  This try/catch message should probably be more specific in what it is trying to catch, or emit a more generally useful, and generic, message upon exception.

Fix docker config typo + error catching

---

python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py

Previous version had issues with processing descriptors using Caffe plugin. This was due to a non-deterministic return from the asynchronous image pixel loading / transforming when the parallel method was changed from using ``multiprocessing.Pool`` to ``smqtk.utils.parallel.parllel_map``. The ``ordered=True`` parameter has been added, causing results to compare to those before than function change.

Fix caffe nondeterministic image loading

---

docs/release_notes/v0.7.0.md
python/smqtk/representation/descriptor_element/local_elements.py
python/smqtk/tests/algorithms/classifier/test_libsvm.py
python/smqtk/tests/algorithms/nn_index/test_NNI_FLANN.py
python/smqtk/tests/algorithms/nn_index/test_NNI_abstract.py
python/smqtk/tests/algorithms/nn_index/test_NNI_lsh.py
python/smqtk/tests/algorithms/relevancy_index/test_iqr_svm_hik.py
python/smqtk/tests/representation/DescriptorElement/test_DescriptorMemoryElement.py
python/smqtk/tests/representation/DescriptorIndex/test_DI_memory.py
python/smqtk/tests/representation/test_DescriptorElementFactory.py

Basically, simplify the in-memory descriptor element implementation. The original intention of in-memory descriptors is that there is no storage somewhere that's maintaining the vector. The previous implementation kept everything in memory in the background when the most common use case for using in-memory descriptors is just to store a vector locally and temporarilly.
This should also address the memory "leak" that can be seen when running a nearest-neighbor or iqr service over time when configured to use in-memory descriptor element generation (they're never destroyed/removed from global cache after generation).

Revise in-memory descriptor element representation

---

docs/release_notes/v0.7.0.md
python/smqtk/__init__.py
python/smqtk/algorithms/__init__.py
python/smqtk/iqr/__init__.py
python/smqtk/representation/__init__.py

Thanks @jeffbaumes for the suggestion. My only discomfort with this is that a bunch if stuff is them loaded, but maybe that's fine. I think I had initially looked at stuff like scikit-learn which didn't import most of its sub-modules when doing an ``import sklearn``. But then again, we're using plugins here for algorithms and backends, so ideally the bulk of loadable content lives in there, which is correctly not being loaded initially. I think I'll want to trim down some of the utility importing that occurs in ``smqtk/utils/__init__.py`` since I think most of it is not used from that scope.

Added some initial implicit imports to make core content available

---

.travis.yml
docs/installation.rst
requirements.docs.conda.txt
requirements.docs.txt
requirements.pip.txt
requirements.txt

Only retaining one requirements file for each separation as per the norm
with packages on PYPI. This is also motivated by wheel packages being
more commonly found via pip (e.g. with numpy, scipy, etc.), eliminating
the primary desire to separate package installations between conda/pip.
If it is desired to install packages through conda, users will have to
decide which packages they want to separate out.

Removed conda/pip separated requirements files

---

CMakeLists.txt
docker/smqtk_services/Dockerfile

Removed requirements file installation as it seems redundant with
installation via pip, which resolves dependencies.

Removed lingering references to conda-variant requirements txt

---

docs/release_notes/v0.7.0.md
python/smqtk/algorithms/classifier/__init__.py
python/smqtk/bin/classifier_kfold_validation.py
python/smqtk/representation/descriptor_element/local_elements.py
python/smqtk/tests/representation/DescriptorElement/test_DescriptorFileElement.py

Breaks backward compatibility with previous DescriptorFileElement storages. This can be resolved by traversing the directory tree and re-creating the elements from the cached file contents. Full UUIDs were and are still encoded in the file name.

Fix element default and storage

---

docs/release_notes/v0.7.0.md
python/smqtk/bin/nearest_neighbors.py
setup.py

This adds a script under the alias `smqtk-nearest-neighbors` for finding
the nearest neighbors given a nearest neighbor index.
There are a number of ways this script could be improved in the future:
1) The computation could be parallelized with the caveat that the descriptor index is stored in a way that wouldn't get bogged down from random seeks.
2) Using a list of uuids should be batched to reduce the amount of queries to the descriptor index
3) Some level of support for picking up where it left off. This is harder to do since it's writing to stdout or a file, but maybe a limit/offset syntax, or in the future it can support storing them in a database table.
4) ~~Support for getting **all** nearest neighbors~~

Add minimal script for finding nearest neighbors

---

python/smqtk/representation/data_element/file_element.py
setup.py

If importable, try to use file-magic mime-type identification from file
bytes first. This should be more performant that use of tika and is more
robust than just checking file name extension string.

Added optional use of file-magic module for DataFileElement

---

python/smqtk/bin/check_images.py
python/smqtk/bin/compute_many_descriptors.py
python/smqtk/tests/utils/test_image_utils.py
python/smqtk/utils/image_utils.py
setup.py

Add check images script

---

docker/smqtk_services/Dockerfile

This line was resulting in the following error during docker build:
`Error response from daemon: Unknown instruction: &&`
This seems to have become a problem since Docker 1.13.

Add backslash to line continuation for Dockerfile

---

python/smqtk/algorithms/nn_index/lsh/functors/itq.py

@Purg I think this is the last place (excluding tests) that forcibly sets multiprocessing to `True`.

Alter lsh.functors.itq.fit to optionally use multiprocessing

---

python/smqtk/algorithms/descriptor_generator/caffe_descriptor.py

This will make it so that `compute_descriptor_async` will pass through the
`use_mp` keyword to `_process_batch`. This will allow certain tasks (such
as Celery workers) that don't allow multiprocessing to switch the
parallelism to use threading instead.

Adjust _process_batch to respect use_mp setting

---

python/smqtk/representation/data_element/file_element.py
python/smqtk/tests/representation/DataElement/test_DataFileElement.py

``file-magic`` obviously fails if there are no bytes to introspect for a
file type. Fixed tests to pass when file-magic is installed.

Only use magic if the input filepath actually points to a real file

---

python/smqtk/tests/utils/test_factors.py
python/smqtk/utils/factors.py

Randomly found some time to add a caching optimization to the sieve-of-eratosthenes function for finding primes when I was playing with coding problems on codewars. This improvement causes successive calls to the function, and other functions that use soe, to be faster on average.
Still needs locking around globals still for thread safety.

Add incremetal caching to sieve_of_eratosthenes function

---

docs/release_notes/pending_release.md
python/smqtk/representation/descriptor_index/postgres.py
python/smqtk/utils/postgres.py

Addresses issue #334 where a call to the connection helper was not updated after an API update.
Also fixed a bug in the helper class where the connection was being referenced before it may have been initialized.

Fix postgres di batch execute

---

.travis.yml
docs/release_notes/pending_release.md

Miniconda was not being used for anything specific so there doesn't seem
to be a reason to not use the travis container system python.  The
current use of miniconda also circumnavigates any python version
settings provided to travis.

Removed miniconda installation

---

docs/release_notes/pending_release.md
python/smqtk/tests/algorithms/relevancy_index/test_svm_hik.py

Descriptors 2/6 and 3/4 are equidistant in the test and may be in either order.

Fix libsvm-hik relevancy index test

---

python/smqtk/algorithms/relevancy_index/libsvm_hik.py
python/smqtk/tests/algorithms/relevancy_index/test_svm_hik.py

Fix rank pool score ordering issue when ``use_libsvm == True``.  Applies the same probability inversion check as the other code path, but using the same mechanism as the ``use_libsvm`` path.

Add equivalent probability flip check to use_libsvm=true path

---

docs/release_notes/pending_release.rst
python/smqtk/web/search_app/modules/login/templates/login.html

Minor fix that corrects the "off" value being set to the autocomplete flag in the login form.

Fix boolean flag passed to HTML input autocomplete property

---

docs/release_notes/pending_release.rst
python/smqtk/algorithms/nn_index/hash_index/sklearn_balltree.py

Usage of parent class' ``__getstate__`` is used with less specificity to
allow for compatibility into version 0.20.

Fix balltree HashIndex plugin save/load

---

docs/release_notes/pending_release.rst
python/smqtk/algorithms/nn_index/lsh/__init__.py
python/smqtk/bin/compute_hash_codes.py
python/smqtk/representation/key_value/memory.py
python/smqtk/tests/algorithms/nn_index/test_NNI_lsh.py

Also update _build_index and _remove_from_index to use batching.

Fix LSH updating of hash2uuid key-value store when frozenset based

---

docs/conf.py
docs/release_notes/pending_release.rst
requirements.docs.txt

The mocking that occurred in the ``docs/conf.py`` is brittle to changes in the python code when new sub-modules are imported and only adds the ability to build the documentation without an install of the SMQTK python package and its code dependencies.  This mocking was previously required because ReadTheDocs had previously only installed the requirements from the specificly configured requirements file.  Now, however, the whole SMQTK package is being installed via a ``python setup.py install --force`` command, thus installing all of SMQTK's core dependencies in the process of building the docs.

Update documentation python deps, remove mocking from conf.py

---

devops/docker/smqtk_iqr_playground/Dockerfile.cpu.df
devops/docker/smqtk_iqr_playground/Dockerfile.gpu-cuda8.0-cudnn6.df
devops/docker/smqtk_iqr_playground/matplotlibrc
docs/release_notes/pending_release.rst

It seems to be the case that somewhere the TkAgg backend is being
selected as the default backend to be used even though there is no
python tk module required to use it. This causes an exception when
``matplotlib.pyplot`` is imported without intervention. We add here a
``.config/matplotlib/matplotlibrc`` file to explicitly request the use
of the Agg backend which does not cause exceptions.

Add matplotlibrc to specify use of AGG backend explicitly

---

docs/conf.py
docs/readthedocs-reqs.txt

Recent branch broke readthedocs build due to a requirements mismatch when smqtk is locally installed during the build.

Fix readthedocs build
